FinalExam.MVC/Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using FinalExam.Core.Entities;
using Google.Apis.Admin.Directory.directory_v1.Data;
using Roles = FinalExam.Core.Entities.Roles;

namespace FinalExam.Areas.Admin.Controllers;

[Area("Admin")]
[Authorize(Roles = nameof(Roles.Admin))]
public class DashboardController : Controller
{
    public IActionResult Index()
    {
        return View();
    }
}

FinalExam.MVC/Areas/Admin/ViewComponents/AdminHeaderViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using FinalExam.BL.ViewModels.Auths;

namespace FinalExam.MVC.Areas.Admin.ViewComponents;

public class AdminHeaderViewComponent : ViewComponent
{
    public async Task<IViewComponentResult> InvokeAsync()
    {
        UserAdminInfoVM vm = new();
        vm.IsAuth = HttpContext.User?.Identity?.IsAuthenticated ?? false;
        vm.Username = HttpContext.User?.FindFirst(ClaimTypes.Name)?.Value ?? "unknown"; // Fullname is custom given property outside AspNet.Identity
        return View(vm);
    }
}

FinalExam.MVC/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>@ViewBag.Title</title>

    <!-- Custom fonts for this template-->
    <link href="~/admin/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/admin/css/sb-admin-2.min.css" rel="stylesheet">
    @RenderSection("style", false)
</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" asp-controller="Dashboard" asp-action="Index">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
                </div>
                <div class="sidebar-brand-text mx-3">SB Admin <sup>2</sup></div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item">
                <a class="nav-link" asp-controller="Dashboard" asp-action="Index">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Nav Item - Sliders -->
            <li class="nav-item">
                <a class="nav-link" asp-controller="Slider" asp-action="Index">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Sliders</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider"> 
            
            <!-- Nav Item - Brands -->
            <li class="nav-item">
                <a class="nav-link" asp-controller="Brand" asp-action="Index">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Brands</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Nav Item - Brands -->
            <li class="nav-item">
                <a class="nav-link" asp-controller="Product" asp-action="Index">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Products</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                @await Component.InvokeAsync("AdminHeader")

                <!-- Begin Page Content -->
                <div class="container-fluid">
        @RenderBody()
    </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2020</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" asp-action="Logout" asp-controller="Account" asp-area="default">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="~/admin/vendor/jquery/jquery.min.js"></script>
    <script src="~/admin/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/admin/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/admin/js/sb-admin-2.min.js"></script>

</body>

</html>